# Generated by Django 2.2 on 2020-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0003_gal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ban_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='notice/')),
            ],
            options={
                'db_table': 'Bann',
            },
        ),
    ]
