# Generated by Django 2.2 on 2020-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0004_ban_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'Banner_up',
            },
        ),
        migrations.DeleteModel(
            name='ban_me',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
