# Generated by Django 2.2 on 2020-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0005_auto_20201203_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_title', models.CharField(max_length=20)),
                ('images', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'Gallery_up',
            },
        ),
        migrations.DeleteModel(
            name='Gal',
        ),
    ]
