# Generated by Django 2.2 on 2020-12-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0006_auto_20201203_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('notice_file', models.FileField(upload_to='notice/')),
            ],
            options={
                'db_table': 'Notice_up',
            },
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
