# Generated by Django 2.2 on 2020-12-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0008_auto_20201203_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
