# Generated by Django 2.2 on 2020-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0009_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('attach_file', models.FileField(upload_to='notice/')),
            ],
        ),
        migrations.DeleteModel(
            name='notice_up',
        ),
    ]
