# Generated by Django 2.2 on 2020-12-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_last', '0010_auto_20201203_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery_up',
            new_name='Gallery',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='images_g',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='images_title',
            new_name='title_g',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table=None,
        ),
    ]
